export const PLACE_MANAGEMENT_REPOSITORY = Symbol('PLACE_MANAGEMENT_REPOSITORY');
export const PLACE_MANAGEMENT_EVENT_BUS = Symbol('PLACE_MANAGEMENT_EVENT_BUS');
export const PLACE_CATALOG_REPOSITORY = Symbol('PLACE_CATALOG_REPOSITORY');
