export const PLACE_REPOSITORY = Symbol('PLACE_REPOSITORY');
export const ML_RECOMMENDATION_PORT = Symbol('ML_RECOMMENDATION_PORT');
export const USER_TRIP_CONTEXT_PORT = Symbol('USER_TRIP_CONTEXT_PORT');
